### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by gouemoolaf28** [gouemoregis/github-crash-course#1]
I think it looks better with a color that goes toward orange

The title style should look like this:

```css
h1 {
  color: #d48d12;
}
```
